### PR TITLE
[TESTS:] Add utils tests

### PR DESCRIPTION
**Pull request by ByteOtter**
# What does this PR change?

This PR adds unittests to all functions of `utils.py`.

Tick the applicable box:
- [ ] Add new feature
- [ ] Add language support
- [ ] UI improvement
- [ ] Security changes
- [x] Tests
<br/>

- [ ] General Maintenance

## UI changes

- No changes

 - [x] DONE

## Links

Fixes: #19 

- [x] DONE

## Documentation

- No documentation needed
<br/>

- [x] DONE

### CODE REVIEW

**Review by tiltingpenguin — CHANGES_REQUESTED** [review]
Sorry, I should have given you more pointers for the tests. What you wrote are mostly integration tests, which belong somewhere else. Let me write you one of the unit tests to build off of

**Comment by tiltingpenguin** [comment]
I just added a test for the load_json function. You want to do this for all functions. Set expected return values, patch all other function that the function to test calls (you can also do it with the @patch decorator like here: https://docs.python.org/3/library/unittest.mock.html#where-to-patch ) and then assert that the return value is as expected

**Comment by ByteOtter** [comment]
> I just added a test for the load_json function. You want to do this for all functions. Set expected return values, patch all other function that the function to test calls (you can also do it with the @ patch decorator like here: https://docs.python.org/3/library/unittest.mock.html#where-to-patch ) and then assert that the return value is as expected

Thank you for your help. I will put the tests I have written into a different module `integration_tests` as you have suggested and take a closer look at the documentation again. Seems like I misunderstood something somewhere.

**Review by tiltingpenguin — APPROVED** [review]
LGTM

**Pull request merged**
